// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pada from "./pada.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Krama from "./krama.mjs";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function reducer(_state, action) {
  return {
          words: action._0
        };
}

var initialState = {
  words: []
};

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  React.useEffect((function () {
          fetch("/hindi_curated.json").then(function (prim) {
                        return prim.text();
                      }).then(function (text) {
                      return Promise.resolve(JSON.parse(text));
                    }).then(function (words) {
                    return Promise.resolve(Belt_Array.shuffle(words));
                  }).then(function (words) {
                  words.length = 24;
                  return Promise.resolve(words);
                }).then(function (words) {
                return Promise.resolve(Curry._1(dispatch, /* SetWords */{
                                _0: words
                              }));
              });
          
        }), []);
  return React.createElement(React.Fragment, undefined, React.createElement(Pada.make, {
                  words: state.words
                }), React.createElement(Krama.make, {
                  words: state.words
                }));
}

var make = App;

export {
  reducer ,
  initialState ,
  make ,
  
}
/* Pada Not a pure module */
