// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Krama(Props) {
  var words = Props.words;
  var list = Belt_Array.mapWithIndex(words, (function (index, word) {
          var number = index + 1 | 0;
          return React.createElement("div", {
                      key: String(number),
                      className: "rounded bg-green-400 text-gray-50 font-semibold pb-4 text-center text-xl md:text-3xl sm:text-xl"
                    }, React.createElement("div", {
                          className: "text-xs text-left text-opacity-25"
                        }, React.createElement("div", {
                              className: "bg-black px-1 tabluar-nums"
                            }, String(number))), React.createElement("div", {
                          className: "pt-2"
                        }, word));
        }));
  var krama_list = function (list) {
    return Belt_Array.concat(Belt_Array.reduceWithIndex(list, [], (function (acc, _value, i) {
                      return Belt_Array.concat(acc, [
                                  list[i],
                                  list[i + 1 | 0]
                                ]);
                    })), [list[list.length - 1 | 0]]);
  };
  return React.createElement("div", {
              className: "p-4 container mx-auto"
            }, React.createElement("h1", {
                  className: "text-4xl pb-4"
                }, "क्रम पाठ"), React.createElement("div", {
                  className: "grid grid-cols-2 gap-4"
                }, krama_list(list)));
}

var make = Krama;

export {
  make ,
  
}
/* react Not a pure module */
