// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Pada(Props) {
  var words = Props.words;
  var list = Belt_Array.mapWithIndex(words, (function (index, word) {
          return React.createElement("div", {
                      key: String(index),
                      className: "rounded bg-green-400 text-gray-50 font-semibold pb-4 text-center text-xl md:text-3xl sm:text-xl"
                    }, React.createElement("div", {
                          className: "text-xs text-left text-opacity-25"
                        }, React.createElement("div", {
                              className: "bg-black px-1 tabluar-nums"
                            }, String(index + 1 | 0))), React.createElement("div", {
                          className: "pt-2"
                        }, word));
        }));
  return React.createElement("div", {
              className: "p-4 container mx-auto"
            }, React.createElement("h1", {
                  className: "text-4xl pb-4"
                }, "पद पाठ"), React.createElement("div", {
                  className: "grid grid-cols-3 lg:grid-cols-8 md:grid-cols-6 sm:grid-cols-6 gap-4"
                }, list));
}

var make = Pada;

export {
  make ,
  
}
/* react Not a pure module */
