// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../utils.mjs";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Samhita(Props) {
  var words = Props.words;
  var list = Belt_Array.mapWithIndex(words, (function (index, word) {
          return Utils.renderWord(index + 1 | 0, word, "bg-green-400", "");
        }));
  return React.createElement("div", {
              className: "p-4 container mx-auto"
            }, React.createElement("h1", {
                  className: "text-4xl pb-4"
                }, "संहिता पाठ"), React.createElement("div", {
                  className: "grid grid-cols-3 lg:grid-cols-8 md:grid-cols-6 sm:grid-cols-6 gap-4"
                }, list));
}

var make = Samhita;

export {
  make ,
  
}
/* Utils Not a pure module */
