// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function reducer(_state, action) {
  return {
          words: action._0
        };
}

var initialState = {
  words: []
};

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  React.useEffect((function () {
          fetch("/hindi_curated.json").then(function (prim) {
                        return prim.text();
                      }).then(function (text) {
                      return Promise.resolve(JSON.parse(text));
                    }).then(function (words) {
                    return Promise.resolve(Belt_Array.shuffle(words));
                  }).then(function (words) {
                  words.length = 24;
                  return Promise.resolve(words);
                }).then(function (words) {
                return Promise.resolve(Curry._1(dispatch, /* SetWords */{
                                _0: words
                              }));
              });
          
        }), []);
  var list = Belt_Array.mapWithIndex(match[0].words, (function (index, word) {
          return React.createElement("div", {
                      key: String(index),
                      className: "rounded bg-green-400 text-gray-50 font-semibold pb-4 text-center text-xl md:text-3xl sm:text-xl"
                    }, React.createElement("div", {
                          className: "text-xs text-left text-opacity-25"
                        }, React.createElement("div", {
                              className: "bg-black px-1"
                            }, String(index + 1 | 0))), React.createElement("div", {
                          className: "pt-2"
                        }, word));
        }));
  return React.createElement("div", {
              className: "p-4 container mx-auto"
            }, React.createElement("div", {
                  className: "grid grid-cols-3 lg:grid-cols-8 md:grid-cols-6 sm:grid-cols-6 gap-4"
                }, list));
}

var make = App;

export {
  reducer ,
  initialState ,
  make ,
  
}
/* react Not a pure module */
