// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function reducer(_state, action) {
  return {
          words: action._0
        };
}

var initialState = {
  words: []
};

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  React.useEffect((function () {
          fetch("/hindi_curated.json").then(function (prim) {
                        return prim.text();
                      }).then(function (text) {
                      return Promise.resolve(JSON.parse(text));
                    }).then(function (words) {
                    return Promise.resolve(Belt_Array.shuffle(words));
                  }).then(function (words) {
                  words.length = 24;
                  return Promise.resolve(words);
                }).then(function (words) {
                return Promise.resolve(Curry._1(dispatch, /* SetWords */{
                                _0: words
                              }));
              });
          
        }), []);
  var list = Belt_Array.mapWithIndex(match[0].words, (function (index, word) {
          return React.createElement("div", {
                      key: String(index),
                      className: "rounded bg-green-400 text-gray-50 font-semibold text-center py-4"
                    }, word);
        }));
  return React.createElement("div", {
              className: "p-8"
            }, React.createElement("div", {
                  className: "grid grid-cols-8 gap-4"
                }, list));
}

var make = App;

export {
  reducer ,
  initialState ,
  make ,
  
}
/* react Not a pure module */
