// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";

var hindi_words = Fs.readFileSync("./hindi/hindi_curated.csv").toString();

var lines = hindi_words.split("\n");

export {
  hindi_words ,
  lines ,
  
}
/* hindi_words Not a pure module */
