// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";

var hindi_words = Fs.readFileSync("./hindi/hindi_curated.csv").toString();

var lines = hindi_words.split("\n");

var Hindi = {
  hindi_words: hindi_words,
  lines: lines
};

export {
  Hindi ,
  
}
/* hindi_words Not a pure module */
