// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as React from "react";

var hindi_words = Fs.readFileSync("./hindi/hindi_curated.csv").toString();

var lines = hindi_words.split("\n");

var Hindi = {
  hindi_words: hindi_words,
  lines: lines
};

function Index(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var make = Index;

export {
  Hindi ,
  make ,
  
}
/* hindi_words Not a pure module */
