// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function renderWord(number, word, bgColorClass, textColorClass) {
  var className = "rounded text-gray-50 font-semibold pb-4 text-center text-xl md:text-3xl sm:text-xl " + bgColorClass + " " + textColorClass;
  return React.createElement("section", {
              key: String(number),
              className: className
            }, React.createElement("div", {
                  className: "text-xs text-left text-opacity-25"
                }, React.createElement("div", {
                      className: "bg-gray-500 px-1 tabluar-nums text-gray-50"
                    }, String(number))), React.createElement("div", {
                  className: "pt-2"
                }, word));
}

export {
  str ,
  renderWord ,
  
}
/* react Not a pure module */
